repos:
  - repo: https://github.com/biomejs/pre-commit
    rev: "v1.9.4"
    hooks:
      - id: biome-check
      - id: biome-lint
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
